<div class="head-nd-links flex-column pt-3">
    <h5><b>Dietry Supplements with BCCA & EAA Amino acids</b></h5>
    <p>In connection with fitness and bodybuilding one does not get around the amino acids.There are
        different
        products and compositions that are usually not making sense, unless you know what is being refered
        to.
        The best known examples are BCAA(Branched Chain Amino Acids) and EAA(Esseential Amino Acids).</p>
    <p>Branched Chain Amino Acids contain 3 important amino acids for affecting mTOR(protein synthesis)these
        are
        L-Leucine,L-Valine and L-Isoleucine, EAA Essential Amino Acids - contains 9 Essential Amino acids.
        including the before mentioned three L-phenylanine, Threonine, L-Lysine, L-Histidine & L-Tryptophan.
        Together the 9 essential amino acids reperesent the complete chain nedded to build muscle tissue.
    </p>
</div>

<div class="card-group">
    <div class="row row-cols-2 g-4">
        <div class="col">
            <div class="card">
                <img src="<?php echo $block->getViewFileUrl('images/person1.png') ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">JENNI AASKO</h5>
                    <span class="card-text">Kundeservie</span>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <img src="<?php echo $block->getViewFileUrl('images/person2.png') ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">DANIEL EMIL USSING</h5>
                    <span class="card-text">Produckt Specialist</span>
                </div>
            </div>
        </div>
    </div>
</div>