<div class="product-specialist-container">
    <div class="image-container">
        <img src="<?php echo $block->getViewFileUrl('images/person2.png') ?>" class="" alt="...">
    </div>
    <div class="details-container">
        <h4>Daniel Emil Ussing</h4>
        <p>Pharmacy Technician & Product Specialist</p>
        <p>Educated at the Danish School of Pharmacy Technicians & Acting specialist in Dietary Supplements.
            If you have any questions about the effects, ingredients or integrity of a product, please don't hesitate
            to contact me. Visit my LinkedIn Profile for References</p>
        <a href="">Read more<svg fill="#e00514" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-49.5 -49.5 429.00 429.00" xml:space="preserve" stroke="#e00514" stroke-width="16.5"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="0.66"></g><g id="SVGRepo_iconCarrier"> <path id="XMLID_222_" d="M250.606,154.389l-150-149.996c-5.857-5.858-15.355-5.858-21.213,0.001 c-5.857,5.858-5.857,15.355,0.001,21.213l139.393,139.39L79.393,304.394c-5.857,5.858-5.857,15.355,0.001,21.213 C82.322,328.536,86.161,330,90,330s7.678-1.464,10.607-4.394l149.999-150.004c2.814-2.813,4.394-6.628,4.394-10.606 C255,161.018,253.42,157.202,250.606,154.389z"></path> </g></svg></a>
    </div>
</div>